[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
demr = "FMcmweJZFaKd7AKkxVf2tYNakCueebbkcGVmzpHPXsba"

[programs.localnet]
demr = "FMcmweJZFaKd7AKkxVf2tYNakCueebbkcGVmzpHPXsba"

[programs.mainnet]
demr = "FMcmweJZFaKd7AKkxVf2tYNakCueebbkcGVmzpHPXsba"


[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./id.json"

[scripts]
demr = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 scripts/demr.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/staking_phase_2.ts"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "./test-libs/metadata.so"
