[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
demr = "CLjotqSXscvfm7FTfr1NoR9tz45EeFMm6nCYNRBcYpd4"
mock_nft = "C5QPdEnjyHBvNXuAZcZvwH83wXcCewr7tzaZWiePH1qv"
staking_phase_2 = "21NP2mv5RqPdkdvDJYrAWWwcVsUkrMUvWfdw3aNftDBT"

[programs.localnet]
mock_nft = "C5QPdEnjyHBvNXuAZcZvwH83wXcCewr7tzaZWiePH1qv"
staking_phase_2 = "21NP2mv5RqPdkdvDJYrAWWwcVsUkrMUvWfdw3aNftDBT"

[programs.mainnet]
mock_nft = "C5QPdEnjyHBvNXuAZcZvwH83wXcCewr7tzaZWiePH1qv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "./id.json"

[scripts]
demr = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/mock_demr.ts"
mock_nft = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/mock_nft.ts"
staking = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/staking.ts"
staking_phase_2 = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 scripts/staking_phase_2.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/staking_phase_2.ts"
test_mpl = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/mpl_api_test.ts"


[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "./test-libs/metadata.so"
